### PR TITLE
Dotnet

### PR DESCRIPTION
**Pull request by SamuelCox**
Wrote a test for dotnet after @DavidFowl 's twitter thread raised interesting discussions around dns on .net

### CODE REVIEW

**Comment by SamuelCox** [comment]
THink this needs a little work still, I'm struggling to get it to run properly

**Comment by SamuelCox** [comment]
Just realised I did a ton of stuff wrong, abandoning, might take another stab sometime

**Comment by davidfowl** [comment]
If you need help let me know

**Comment by SamuelCox** [comment]
Cheers @davidfowl, I'll put in a pr tomorrow once I'm a bit less tired. Mostly docker isn't playing nice with my machine so I can't test it, and I dumbly directly used the dns class instead of http like the other tests. I'll make another PR with the second fixed but might need someone else to run it if I can't resolve the docker issues with this repo on my machine.

**Comment by SamuelCox** [comment]
@davidfowl Hey, any chance you could take a look at this https://github.com/SamuelCox/denial-by-dns/tree/dotnet-support and help me figure out why in the world the docker build doesn't work when calling the make file?

Initially I had the standard https://github.com/dotnet/dotnet-docker/tree/main/samples/dotnetapp from here, but that didn't work, so have been trying to bring it more in line with the current examples and has not worked at all

**Pull request closed without merging**
